-- Zameen Minti Project - Supabase SQL Schema v34
-- Supabase Dashboard > SQL Editor ਵਿੱਚ ਇਹ ਪੂਰਾ SQL run ਕਰੋ.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  mobile text,
  email text,
  role text not null default 'client' check (role in ('client','owner','admin')),
  plan text not null default 'free' check (plan in ('free','premium')),
  created_at timestamptz default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  client_id uuid references public.profiles(id) on delete cascade,
  sender_id uuid references auth.users(id) on delete cascade,
  sender_role text not null check (sender_role in ('client','owner','admin')),
  message text not null,
  read_by_owner boolean default false,
  read_by_client boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  client_id uuid references public.profiles(id) on delete set null,
  report_type text not null,
  report_data jsonb not null,
  created_at timestamptz default now()
);

create table if not exists public.land_records (
  id bigint generated by default as identity primary key,
  client_id uuid references public.profiles(id) on delete cascade,
  title text,
  village text,
  district text,
  area_data jsonb,
  map_points jsonb,
  created_at timestamptz default now()
);

create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  client_id uuid references public.profiles(id) on delete set null,
  page text,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;
alter table public.reports enable row level security;
alter table public.land_records enable row level security;
alter table public.visits enable row level security;

-- profiles policies
drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile" on public.profiles
for select using (auth.uid() = id or exists(select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin')));

drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile" on public.profiles
for update using (auth.uid() = id);

drop policy if exists "users can insert own profile" on public.profiles;
create policy "users can insert own profile" on public.profiles
for insert with check (auth.uid() = id);

-- owner helper
create or replace function public.is_owner()
returns boolean
language sql
security definer
as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role in ('owner','admin'));
$$;

-- messages policies
drop policy if exists "clients read own messages owners read all" on public.messages;
create policy "clients read own messages owners read all" on public.messages
for select using (client_id = auth.uid() or public.is_owner());

drop policy if exists "clients insert own messages owners insert replies" on public.messages;
create policy "clients insert own messages owners insert replies" on public.messages
for insert with check (
  (sender_id = auth.uid() and client_id = auth.uid() and sender_role = 'client')
  or
  (sender_id = auth.uid() and public.is_owner() and sender_role in ('owner','admin'))
);

drop policy if exists "owners update messages" on public.messages;
create policy "owners update messages" on public.messages
for update using (public.is_owner() or client_id = auth.uid());

-- reports policies
drop policy if exists "clients read own reports owners read all" on public.reports;
create policy "clients read own reports owners read all" on public.reports
for select using (client_id = auth.uid() or public.is_owner());

drop policy if exists "clients insert own reports" on public.reports;
create policy "clients insert own reports" on public.reports
for insert with check (client_id = auth.uid() or client_id is null or public.is_owner());

-- land records policies
drop policy if exists "clients manage own land records owners all" on public.land_records;
create policy "clients manage own land records owners all" on public.land_records
for all using (client_id = auth.uid() or public.is_owner())
with check (client_id = auth.uid() or public.is_owner());

-- visits policies
drop policy if exists "any authenticated insert visits" on public.visits;
create policy "any authenticated insert visits" on public.visits
for insert with check (auth.uid() = client_id or client_id is null);

-- Realtime enable
alter publication supabase_realtime add table public.messages;

-- After creating your owner account from site signup/login,
-- run this with your owner email:
-- update public.profiles set role='owner', plan='premium' where email='YOUR_EMAIL_HERE';
